services:
  db:
    image: postgres:17
    container_name: odoo19_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - automation

  odoo:
    image: odoo:19.0
    container_name: odoo19_app
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: db
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-odoo}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      ODOO_ADMIN_PASSWD: ${ODOO_ADMIN_PASSWD}
    networks:
      - automation

volumes:
  postgres_data:
  odoo_data:

networks:
  automation:
    name: automation-network
