[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$krK21lpLyRmD0Nrb.19rrQ$JGvQNmGgZIYjXETIyaiMLLhna8bb.ObbNTfh1goL0WqDGDhXBBVs2ENsRrkhiRjstJFbMvI9YH2yL5UTiUCR2g

