[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$1rrXurc2BgBAyJlTKuX8Pw$Bv8OUk2R07NmqG4VtuiV6kae/dRoHSZKanUwmINxZWV08RjnN3416421DK/SrxKVhLVjGcq/AyDDOZiWW1YgTQ

