[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$YUwpRWiNsfbeO4dQytl7Tw$4SjndOOlu5A/eSc4dn1H/TDbivw472vDPBxkFnOR/bQufi.csyq3P5tfcuXCRbIJ8REU9akdeWHy0lLcEElZDw

